/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package component;

/**
 *
 * @author MSI
 */
public class jFrameMuaVe extends javax.swing.JFrame {

    /**
     * Creates new form jFrameMuaVe
     */
    public jFrameMuaVe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThanhToan = new javax.swing.JButton();
        lbCCCD = new javax.swing.JLabel();
        jtGia = new javax.swing.JTextField();
        lbTienTra = new javax.swing.JLabel();
        lbSdt = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbSLV = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        ifCCCD = new javax.swing.JLabel();
        ifHoTen = new javax.swing.JLabel();
        ifSdt = new javax.swing.JLabel();
        ifSLV = new javax.swing.JLabel();
        ifTongTien = new javax.swing.JLabel();
        btnTreoD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThanhToan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");

        lbCCCD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbCCCD.setText("CCCD:");

        jtGia.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jtGia.setPreferredSize(new java.awt.Dimension(91, 40));
        jtGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtGiaKeyReleased(evt);
            }
        });

        lbTienTra.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbTienTra.setText(" ");

        lbSdt.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbSdt.setText("Số điện thoại:");

        lbHoTen.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbHoTen.setText("Họ tên:");

        lbSLV.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbSLV.setText("Số lượng vé:");

        lbTongTien.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbTongTien.setText("Tổng tiền:");

        ifCCCD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifCCCD.setText(" ");

        ifHoTen.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifHoTen.setText(" ");

        ifSdt.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifSdt.setText(" ");

        ifSLV.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifSLV.setText(" ");

        ifTongTien.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifTongTien.setText(" ");

        btnTreoD.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnTreoD.setText("Treo đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCCCD)
                            .addComponent(lbHoTen)
                            .addComponent(lbSdt)
                            .addComponent(lbSLV)
                            .addComponent(lbTongTien))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ifTongTien)
                            .addComponent(ifSLV)
                            .addComponent(ifSdt)
                            .addComponent(ifHoTen)
                            .addComponent(ifCCCD))))
                .addGap(37, 37, 37)
                .addComponent(lbTienTra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnTreoD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCCCD)
                    .addComponent(ifCCCD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen)
                    .addComponent(ifHoTen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSdt)
                    .addComponent(ifSdt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSLV)
                    .addComponent(ifSLV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongTien)
                    .addComponent(ifTongTien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTienTra))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTreoD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtGiaKeyReleased
        
    }//GEN-LAST:event_jtGiaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameMuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameMuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameMuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameMuaVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameMuaVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTreoD;
    private javax.swing.JLabel ifCCCD;
    private javax.swing.JLabel ifHoTen;
    private javax.swing.JLabel ifSLV;
    private javax.swing.JLabel ifSdt;
    private javax.swing.JLabel ifTongTien;
    private javax.swing.JTextField jtGia;
    private javax.swing.JLabel lbCCCD;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbSLV;
    private javax.swing.JLabel lbSdt;
    private javax.swing.JLabel lbTienTra;
    private javax.swing.JLabel lbTongTien;
    // End of variables declaration//GEN-END:variables
}
